name: My first Workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
           - name: welcome message
             run: echo "Hi Abimel"

           - name: list files
             run: ls

           - name: read files
             run: cat README.md
           

